name : GITHUB ACTIONS avec le maven build
#le on : 
on : 
  push :
       branches: [ "main" ]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: 1ere action Prendre le repertoire pour l'executer  "checker le repository"
          uses : actions/checkout@v3
          
         
        - name: 2eme action Set up JDK 11
          uses: actions/setup-java@v3
          with:
              java-version: '11' 
              distribution: 'adopt ' 

              
              
        - name: step 3 le Build avec Maven 
          run : mvn --batch-mode --update-snapshots package
          #  mvn -B package --file pom.xml

        - name : step 4 afficher tout les fichier avec ceux archiver "-a" dans target
          run : |
                cd target 
                ls -a
  run_tests:
     runs-on: ubuntu-latest
     steps:
      - name: checker le repository
        uses: actions/checkout@v3
        
        
      - name: 2eme action Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11' 
            distribution: 'adopt ' 
          
      - name: Run tests avec Maven
        run: mvn  test
